=== ByteBender747/MiniArc/sfx/sonar-script.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="version-type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9].[0-9].[0-9]" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="amplitude-type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[\-+]{0,1}[0-9]*[.]{0,1}[0-9]*dB" />
            <xs:pattern value="[\-+]{0,1}[0-9]*[.]{0,1}[0-9]*" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="time-type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]*[.]{0,1}[0-9]*%" />
            <xs:pattern value="[\-+]{0,1}[0-9]*[.]{0,1}[0-9]*" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="octave-type">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="-1" />
            <xs:maxInclusive value="9" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="wavefrom-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="sine" />
            <xs:enumeration value="rect" />
            <xs:enumeration value="sawtooth" />
            <xs:enumeration value="rect" />
            <xs:enumeration value="noise" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="modulation-method">
        <xs:restriction base="xs:string">
            <xs:enumeration value="add" />
            <xs:enumeration value="subtract" />
            <xs:enumeration value="multiply" />
            <xs:enumeration value="divide" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="waveform-ctype">
        <xs:attribute name="type" type="wavefrom-type" use="required" />
        <xs:attribute name="frequency" type="xs:double" use="required" />
        <xs:attribute name="amplitude" type="amplitude-type" use="optional" default="1" />
        <xs:attribute name="offset" type="xs:double" use="optional" default="0" />
        <xs:attribute name="phase" type="xs:double" use="optional" default="0" />
    </xs:complexType>
    <xs:complexType name="base-noise-ctype">
        <xs:attribute name="type" type="wavefrom-type" use="required" />
        <xs:attribute name="min-freq" type="xs:double" use="required" />
        <xs:attribute name="max-freq" type="xs:double" use="required" />
        <xs:attribute name="overlays" type="xs:positiveInteger" use="required" />
    </xs:complexType>
    <xs:complexType name="white-noise-ctype">
        <xs:complexContent>
            <xs:extension base="base-noise-ctype">
                <xs:attribute name="min-amp" type="amplitude-type" use="optional" default="0" />
                <xs:attribute name="max-amp" type="amplitude-type" use="optional" default="1" />
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="import-ctype">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="normalize" type="xs:boolean" use="optional" default="false" />
        <xs:attribute name="scale" type="xs:double" use="optional" default="1" />
        <xs:attribute name="offset" type="xs:double" use="optional" default="0" />
    </xs:complexType>
    <xs:complexType name="hull-ctype">
        <xs:attribute name="attack" type="time-type" use="required" />
        <xs:attribute name="sustain" type="time-type" use="required" />
        <xs:attribute name="sustain-level" type="amplitude-type" use="required" />
        <xs:attribute name="min" type="amplitude-type" use="optional" default="-60" />
        <xs:attribute name="max" type="amplitude-type" use="optional" default="0" />
    </xs:complexType>
    <xs:complexType name="linear-ctype">
        <xs:attribute name="min" type="xs:double" use="optional" default="0" />
        <xs:attribute name="max" type="xs:double" use="optional" default="1" />
    </xs:complexType>
    <xs:complexType name="echo-ctype">
        <xs:attribute name="delay" type="xs:double" use="required" />
        <xs:attribute name="decay" type="xs:double" use="required" />
        <xs:attribute name="wet" type="xs:double" use="optional" default="0.5" />
    </xs:complexType>
    <xs:complexType name="hall-ctype">
        <xs:attribute name="room-size" type="xs:double" use="required" />
        <xs:attribute name="decay" type="xs:double" use="required" />
        <xs:attribute name="wet" type="xs:double" use="optional" default="0.3" />
    </xs:complexType>
    <xs:complexType name="gauss-ctype">
        <xs:attribute name="sigma" type="xs:double" use="required" />
        <xs:attribute name="my" type="xs:double" use="optional" default="0" />
        <xs:attribute name="scale" type="xs:double" use="optional" default="1" />
    </xs:complexType>
    <xs:complexType name="sequence-ctype">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="import" type="xs:string" use="required" />
                <xs:attribute name="octave" type="octave-type" use="optional" default="0" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="sonar">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="synthesis">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="initialize" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:choice>
                                        <xs:element name="waveform" type="waveform-ctype" />
                                        <xs:element name="pink-noise" type="base-noise-ctype" />
                                        <xs:element name="red-noise" type="base-noise-ctype" />
                                        <xs:element name="blue-noise" type="base-noise-ctype" />
                                        <xs:element name="white-noise" type="white-noise-ctype" />
                                        <xs:element name="import" type="import-ctype" />
                                        <xs:element name="hull" type="hull-ctype" />
                                        <xs:element name="linear" type="linear-ctype" />
                                        <xs:element name="gauss" type="gauss-ctype" />
                                        <xs:element name="sequence" type="sequence-ctype" />
                                    </xs:choice>
                                    <xs:attribute name="seed" type="xs:integer" use="optional"
                                        default="0" />
                                </xs:complexType>
                            </xs:element>
                            <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="mod-amp">
                                    <xs:complexType>
                                        <xs:choice maxOccurs="unbounded">
                                            <xs:element name="waveform" type="waveform-ctype"
                                                maxOccurs="unbounded" />
                                            <xs:element name="pink-noise" type="base-noise-ctype"
                                                maxOccurs="unbounded" />
                                            <xs:element name="red-noise" type="base-noise-ctype"
                                                maxOccurs="unbounded" />
                                            <xs:element name="blue-noise" type="base-noise-ctype"
                                                maxOccurs="unbounded" />
                                            <xs:element name="white-noise" type="white-noise-ctype"
                                                maxOccurs="unbounded" />
                                            <xs:element name="hull" type="hull-ctype"
                                                maxOccurs="unbounded" />
                                            <xs:element name="import" type="import-ctype"
                                                maxOccurs="unbounded" />
                                            <xs:element name="linear" type="linear-ctype"
                                                maxOccurs="unbounded" />
                                            <xs:element name="gauss" type="gauss-ctype"
                                                maxOccurs="unbounded" />
                                        </xs:choice>
                                        <xs:attribute name="method" type="modulation-method"
                                            use="required" />
                                        <xs:attribute name="normalize" type="xs:boolean"
                                            use="optional"
                                            default="true" />
                                        <xs:attribute name="seed" type="xs:integer" use="optional"
                                            default="0" />
                                    </xs:complexType>
                                </xs:element>
                                <xs:element name="mod-freq">
                                    <xs:complexType>
                                        <xs:choice>
                                            <xs:element name="waveform" type="waveform-ctype"
                                                minOccurs="1"
                                                maxOccurs="unbounded" />
                                        </xs:choice>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                            <xs:element name="echo" type="echo-ctype" minOccurs="0" maxOccurs="1" />
                            <xs:element name="hall" type="hall-ctype" minOccurs="0" maxOccurs="1" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required" />
                        <xs:attribute name="duration" type="xs:double" use="required" />
                        <xs:attribute name="normalize" type="xs:boolean" use="optional"
                            default="true" />
                        <xs:attribute name="private" type="xs:boolean" use="optional"
                            default="false" />
                        <xs:attribute name="repeat" type="xs:positiveInteger" use="optional"
                            default="1" />
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:attribute name="version" use="required" type="version-type" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ByteBender747/MiniArc/sfx/pickup.xml
<?xml version="1.0" encoding="UTF-8"?>
<sonar version="0.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sonar-script.xsd">
    <synthesis id="tone" duration="0" normalize="true">
        <initialize>
            <waveform type="sine" frequency="0" />
        </initialize>
        <mod-amp method="add">
            <waveform type="sawtooth" frequency="0" amplitude="-12dB"/>
            <waveform type="rect" frequency="0" amplitude="-25dB"/>
            <waveform type="sawtooth" frequency="0" amplitude="-16dB" phase="90"/>
        </mod-amp>
    </synthesis>
    <synthesis id="output" duration="0">
        <initialize>
            <sequence import="tone" octave="4">30(C#DD#E)</sequence>
        </initialize>
    </synthesis>
</sonar>

=== ByteBender747/MiniArc/sfx/explosion.xml
<?xml version="1.0" encoding="UTF-8"?>
<sonar version="0.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sonar-script.xsd">
    <synthesis id="output" duration="0.6" normalize="true">
        <initialize seed="54343">
            <white-noise type="sine" min-freq="600" max-freq="2500" overlays="56" max-amp="0.003"/>
        </initialize>
        <mod-amp method="add">
            <pink-noise type="sine" min-freq="10" max-freq="5000" overlays="1250" />
        </mod-amp>
        <mod-amp method="multiply">
            <hull attack="1%" sustain="25%" sustain-level="-1dB" min="-60dB" max="0dB"/>
        </mod-amp>
    </synthesis>
</sonar>

=== ByteBender747/MiniArc/sfx/alien-shot.xml
<?xml version="1.0" encoding="UTF-8"?>
<sonar version="0.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sonar-script.xsd">
    <synthesis id="base" duration=".3">
        <initialize>
            <hull attack="50%" sustain="20%" sustain-level="1" min="1800" max="0.1"/>
        </initialize>
        <mod-freq>
            <waveform type="sine" frequency="125" amplitude="-35dB"/>
            <waveform type="sine" frequency="225" amplitude="-56dB"/>
            <waveform type="rect" frequency="326" amplitude="-48dB"/>
            <waveform type="sawtooth" frequency="422" amplitude="-67dB"/>
            <waveform type="sawtooth" frequency="638" amplitude="-76dB"/>
        </mod-freq>
    </synthesis>
    <synthesis id="output" duration=".3" normalize="true">
        <initialize>
            <import id="base" />
        </initialize>
        <mod-amp method="multiply">
            <hull attack="10%" sustain="10%" sustain-level="-1dB" min="-60dB" max="0dB"/>
        </mod-amp>
        <echo delay="0.1" decay="0.3" wet="0.5" />
    </synthesis>
</sonar>

=== ByteBender747/MiniArc/sfx/charged-shot.xml
<?xml version="1.0" encoding="UTF-8"?>
<sonar version="0.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sonar-script.xsd">
    <synthesis id="first" duration="0.5" normalize="false">
        <initialize>
            <linear min="1000" max="0" />
        </initialize>
        <mod-freq>
            <waveform type="sine" frequency="0"/>
            <waveform type="rect" frequency="20"/>
            <waveform type="sawtooth" frequency="50"/>
        </mod-freq>
        <hall room-size="0.9" decay="0.6"/>
    </synthesis>
    <synthesis id="output" duration="0.3" normalize="true">
        <initialize>
            <linear min="0" max="500"/>
        </initialize>
        <mod-freq>
            <waveform type="sawtooth" frequency="0"/>
            <waveform type="rect" frequency="20"/>
            <waveform type="sine" frequency="50"/>
        </mod-freq>
        <mod-amp method="add">
            <import id="first"/>
        </mod-amp>
        <mod-amp method="multiply">
            <hull attack="20%" sustain="50%" sustain-level="-5dB" min="-60dB" max="1"/>
        </mod-amp>
        <hall room-size="0.7" decay="0.6" wet="0.6"/>
    </synthesis>
</sonar>

=== ByteBender747/MiniArc/sfx/hit-effect.xml
<?xml version="1.0" encoding="UTF-8"?>
<sonar version="0.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sonar-script.xsd">
    <synthesis id="output" duration="0.1" normalize="true">
        <initialize>
            <pink-noise type="sine" min-freq="50" max-freq="3000" overlays="512"/>
        </initialize>
        <mod-amp method="multiply">
            <waveform type="rect" frequency="225" offset="1"/>
        </mod-amp>
        <mod-amp method="add">
            <waveform type="noise" frequency="1" amplitude="-36dB"/>
        </mod-amp>
    </synthesis>
</sonar>

=== ByteBender747/MiniArc/sfx/game-over.xml
<?xml version="1.0" encoding="UTF-8"?>
<sonar version="0.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sonar-script.xsd">
    <synthesis id="tone" duration="0" normalize="true">
        <initialize>
            <waveform type="sine" frequency="320" amplitude="-5dB"/>
        </initialize>
        <mod-amp method="add">
            <waveform type="rect" frequency="100"/>
            <waveform type="sawtooth" frequency="250" amplitude="-10dB"/>
        </mod-amp>
    </synthesis>
    <synthesis id="output" duration="0">
        <initialize>
            <sequence import="tone" octave="1">CBAA</sequence>
        </initialize>
    </synthesis>
</sonar>

=== ByteBender747/MiniArc/sfx/laser-shot.xml
<?xml version="1.0" encoding="UTF-8"?>
<sonar version="0.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/ByteBender747/sonar/refs/heads/main/xsd/sonar-script.xsd">
    <synthesis id="output" duration="0.35" normalize="true">
        <!-- Steep frequency sweep: ~2500Hz down to ~100Hz -->
        <initialize>
            <linear min="2200" max="-200" />
        </initialize>
        <!-- Rect and sawtooth carriers for harsh laser buzz, noise for zap texture -->
        <mod-freq>
            <waveform type="noise" frequency="1" amplitude="0.8"/>
            <waveform type="rect" frequency="300" amplitude="1.0"/>
            <waveform type="rect" frequency="400" amplitude="0.6"/>
            <waveform type="sawtooth" frequency="200" amplitude="0.7"/>
        </mod-freq>
        <!-- Sharp attack, brief sustain, fast decay -->
        <mod-amp method="multiply">
            <hull attack="10%" sustain="10%" sustain-level="-1dB" min="-60dB" max="0dB"/>
        </mod-amp>
        <hall room-size="0.5" decay="1.5" wet="0" />
    </synthesis>
</sonar>

=== ByteBender747/MiniArc/sfx/spawn-effect.xml
<?xml version="1.0" encoding="UTF-8"?>
<sonar version="0.2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sonar-script.xsd">
    <synthesis id="output" duration="1.5" normalize="true">
        <initialize>
            <linear min="50" max="250" />
        </initialize>
        <mod-freq>
            <waveform type="rect" frequency="0" amplitude="0.3"/>
            <waveform type="sawtooth" frequency="0" amplitude="0.3"/>
            <waveform type="rect" frequency="0" amplitude="0.2"/>
        </mod-freq>
        <mod-amp method="add">
            <white-noise type="sine" min-freq="100" max-freq="500" overlays="16" min-amp="0.1" max-amp="0.5"/>
        </mod-amp>
    </synthesis>
</sonar>
